version: "3.2"
services:
  order-service:
    image: ghcr.io/h4t4k4/order-service:latest
    container_name: order-service
    ports:
      - 3000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - rabbitmq_network
  shipping-service:
    image: ghcr.io/h4t4k4/shipping-service:latest
    container_name: shipping-service
    ports:
      - 3001:3001
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - rabbitmq_network
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_container
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: 'exit 0'
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge