version: '2'
services:
  item-app:
    image: ghcr.io/h4t4k4/item-app:v1
    ports:
      - "80:8080"
    depends_on:
      - item-db
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
volumes: 
  app-db: