apiVersion: v1 # Versi API yang didefenisikan
kind: Secret # Jenis Objek K8S
metadata: # Metadata untuk Secret
  name: mongo-credentials # Nama Mongo Credentials
type: Opaque # Tipe data yang akan disimpan pada secret
data: # data yang akan disimpan dalam secret
  MONGO_ROOT_USERNAME: YWRtaW4= 
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==