apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode if needed
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
  storageClassName: standard  # Replace with your storage class name
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-pv
spec:
  capacity:
    storage: 1Gi  # Match PVC request
  accessModes:
    - ReadWriteOnce  # Match PVC access mode
  hostPath:
    path: "/mnt/data"  # Replace with your desired host path
  storageClassName: standard  # Match PVC storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-log-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode if needed
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
  storageClassName: standard  # Replace with your storage class name
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log-pv
spec:
  capacity:
    storage: 1Gi  # Match PVC request
  accessModes:
    - ReadWriteOnce  # Match PVC access mode
  hostPath:
    path: "/mnt/log"  # Replace with your desired host path
  storageClassName: standard  # Match PVC storage class