apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/rabbitmq/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/log/rabbitmq"