apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/rabbitmqdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/rabbitmqlog"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmqdata-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmqlog-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi